name: LAMP
url: https://lampgroup.github.io/

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: faculty
    name: Faculty
  - key: postdoc
    name: Postdocs
  - key: grad
    name: Ph.D Students
#  - key: ra
#    name: Research Assistants
  - key: collab
    name: Collaborators
  - key: alum
    name: Alumni

# Number of news stories on the front page.
front_page_news: 5

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /
  - title: News
    link: /blog.html
  - title: Projects
    link: /research.html
  - title: Publications
    link: /publications.html
  - title: People
    link: /#people
